url: https://jasmcole.github.io
baseurl:

# Site settings
title: jasmcole.github.io
email: jcole730@gmail.com
description: "The personal website of Jason Cole."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c70000
  secondary: 111111
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:jcole730@gmail.com
  - title: mortar-board
    url: http://www3.imperial.ac.uk/johnadamsinstitute/team
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=355904591
  - title: wordpress
    url: http://www.jasmcole.com
  - title: google-plus
    url: https://plus.google.com/112991282536415123341/posts
  - title: twitter
    url: http://twitter.com/jasmcole
  - title: github
    url: http://github.com/jasmcole

press:
  - url: http://www.theguardian.com/science/blog/2015/mar/26/how-particle-accelerator-maths-helped-me-fix-my-wi-fi
    img: guardianlogo.jpg
  - url: http://wordplay.blogs.nytimes.com/2014/09/08/bugs/?_r=0
    img: Icon_NYT.jpg
  - url: http://www.cityam.com/239460/this-scientists-3d-map-of-uk-house-prices-will-make-you-weep-into-your-morning-coffee
    img: Icon_CityAM.png
  - url: http://www.engadget.com/2014/09/01/wifi-physics-signal-reception/#continued
    img: Icon_engadget.png
  - url: http://arstechnica.com/gadgets/2014/08/27/mapping-wi-fi-dead-zones-with-physics-and-gifs/
    img: Icon_ars.png
  - url: http://www.dailymail.co.uk/sciencetech/article-2735856/The-physics-WIFI-ROUTER-Scientist-proves-centre-home-best-signal-strength.html
    img: Icon_DM.png
  - url: http://www.newscientist.com/article/dn27685-new-urbanist-giving-physical-shape-to-invisible-signals.html
    img: NewScientist.jpeg
  - url: http://www.fastcodesign.com/3037975/3-d-printed-lampshades-project-mesmerizing-patterns-with-ancient-cartography-methods
    img: FastCoDesign.png
  - url: http://www.ntv.ru/peredacha/chudo_tehniki/m24780/o333337
    img: NTVCrop.png
  - url: http://petapixel.com/2014/10/13/math-behind-rolling-shutter-phenomenon/
    img: petapixel.jpg

# Build settings
markdown: kramdown
permalink: pretty
